######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 7 19:51:53 2010
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../../src/board.h ../../src/chessboard.h
SOURCES += testchessboard.cpp ../../src/board.cpp ../../src/chessboard.cpp
