######################################################################
# Automatically generated by qmake (2.01a) Sun Mar 7 19:51:29 2010
######################################################################

CONFIG += qtestlib
TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += ../../src/board.h
SOURCES += testboard.cpp ../../src/board.cpp
