#!/bin/bash

if [[ "$1" == "--help" || "$1" == "-h" ]]; then
    echo -e "This is a launcher script for NALCG.\nLaunching can include compiling and debugging."
    echo "Usage:"
    echo -e "    ./NALCG [options]\n\n"
    echo "Options:"
    echo "  --update -u         Run make before launching even if binary exists."
    echo "  --clean -c          Run make clean first"
    echo "  --debug             Launch NALCG in gdb and autorun it."
    echo "  --gdb               Launch NALCG in gdb without autorun."
    echo "  --help -h           Show this help and exit."
    echo -e "\n\nWithout options NALCG will be executed normally"
    exit 0
elif [[ "$1" == "--clean" || "$1" == "-c" ]]; then
    make clean
fi

if [[ ! -f ../bin/NALCG || "$1" == "--update" || "$1" == "-u" ]]; then
    sh ../tools/makefile_updater.sh --all # making sure makefile is up-to-date
    echo "NALCG binary not found or out of date, running make..."
    make -sj5
    if [[ $? != 0 ]]; then
        echo "make failed, NALCG can't be launched"
        echo "You might want to clean before re-compiling, clean by running ./NALCG -c"
        echo "exiting..."
        exit
    fi
fi

cd ../bin
if [[ "$1" == "--debug" ]]; then
    gdb ./NALCG -ex run
elif [[ "$1" == "--gdb" ]]; then
    gdb ./NALCG
else
    ./NALCG
fi
